### ISSUE TITLE
spec_helper broken

### ISSUE THREAD

**Issue by james-marshall314** [learn-co-curriculum/jukebox-cli#12]
In <code>spec_helper.rb</code> the line <code>require_relative '../jukebox'</code>  should be <code>require_relative '../lib/jukebox'</code>.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto due 8/28

**Comment by AnnJohn** [comment]
This issue was raised again- #13 .

Needs to be looked at and resolved soon @SophieDeBenedetto

**Comment by SophieDeBenedetto** [comment]
should be fixed now.
