### ISSUE TITLE
Jukebox test fix

### ISSUE THREAD

**Issue by dougtebay** [learn-co-curriculum/jukebox-cli#13]
Hi, to get the test for Jukebox working it's necessary to change line 1 of spec_helper.rb from "require_relative '../jukebox'" to "require_relative '../lib/jukebox'".

**Comment by AnnJohn** [comment]
Hi @dougtebay and thanks for raising the issue. Since this issue is a duplicate of  #12   I will reference your issue there and will close this. Thanks again.

**Comment by dougtebay** [comment]
Hi Ann, sorry if I'm duplicating an issue that was already raised. The Learn lab links to a different repository where I didn't see any issues listed (https://github.com/learn-co-students/guessing-cli-001-prework-web). Hope I'm driving you crazy with all the feedback!

**Comment by dougtebay** [comment]
*NOT driving you crazy :)
