### ISSUE TITLE
Some confusion with the run method in lib/jukebox.rb

### ISSUE THREAD

**Issue by lwadya** [learn-co-curriculum/jukebox-cli#19]
I'm not sure if this is by design, but the expected structure of the main looping method for lib/jukebox.rb is a bit unclear from the readme. The notes detailing the initial name collection for the script seem to indicate that first section of code should live within the jukebox.rb file outside of any method. Once I took a look at the bin/jukebox executable the expectation of that code being contained within a method called run became obvious, but initially the process was a bit confusing.

**Comment by SophieDeBenedetto** [comment]
hi @lwadya, we just updated the readme with clearer instructions. Hope this helps!
