### ISSUE TITLE
Issue with play method.

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/jukebox-cli#20]
The play command is described as follows:

"The play command should accept a song. It should call a play method. The user can select either the song number/index or the song name. Once the user has selected the song they want to play, the jukebox should output 'Playing Phoenix - 1901' or whatever the song name is."

However, in the spec file, the play method is expected to receive as an argument not a single song name/index but the entire array of song names.

It's also suggested that we create a loop in which commands can be entered:

"How to keep the program running until the exit command is executed (Hint: Loop maybe? Loop upon a condition?)"

However, if you're at the command loop, and enter, say, "play 1", then presumably the play method would need to be called with '1' as an argument in order to properly list the song selected. But if play is only accepting an array of songs, how are you supposed to figure out what the user inputed? The two seem mutually exclusive.

**Comment by SophieDeBenedetto** [comment]
hi @mikeappell, we just updated the readme with some clearer instructions. Let us know if you feel it could use further explanation!

**Comment by mikeappell** [comment]
Hi Sophie, that looks great, a lot clearer to me. Am I correct in saying
that the image of the jukebox program running is new? I don't remember
seeing that the first time around, but then, I might have expunged it from
my mind in frustration (this was the first lesson that really gave me a
hard time.)

Either way, it's a lot clearer now. Thanks!

**Comment by SophieDeBenedetto** [comment]
@mikeappell glad to hear it! as far as i know the picture is not new :)

**Comment by mikeappell** [comment]
Guess I'm just goin' nuts then. Wouldn't be the first time  =)
