### ISSUE TITLE
Getting my program to pass

### ISSUE THREAD

**Issue by halfields** [learn-co-curriculum/jukebox-cli#24]
I built a program for this lab, and ran it in the command line using 'ruby bin/jukebox'. It ran beautifully. I incorporated a loop block with a case statement inside which was conditional upon whatever command was entered from the command line. The loop was exited with a break upon entering the 'exit' command.
As I said it worked great using the command line, but when I tested it using the 'learn' command, I could not get it  to pass the 'help output' part unless I cheapened the program by removing the loop/end statements. With the 'loop/end' statements in, the 'learn suite' ran a long time (about 30 seconds) before it outputted a no memory error for the 'help output' commands.

**Comment by SophieDeBenedetto** [comment]
Hi @halfields, there was a bug in the test suite which should be fixed now. Let us know if you run into further problems!
