### ISSUE TITLE
Missing shebang line

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/jukebox-cli#26]
User: Kevin McCormack

Batch: teacher-fellowship-1015

Current Lesson: Jukebox CLI

Bug Description: I'm not sure if this was part of the challenge/activity, but the /bin/advanced_jukebox would not run because of a missing shebang line. `#!/usr/bin/env ruby` I fixed this in my fork https://github.com/HarlemSquirrel/jukebox-cli-teacher-fellowship-1015/blob/master/bin/advanced_jukebox

**Comment by AnnJohn** [comment]
pull request in that fixes this. thanks.
