### ISSUE TITLE
Add instructions for manual cloning in case learn command fails

### ISSUE THREAD

**Issue by clintonn** [learn-co-curriculum/jukebox-cli#32]
Ran into an issue when using the Learn IDE to clone the jukebox-cli repo — the IDE didn't download the mp3 files correctly, nor did it download the /bin/, /lib/, and /spec/ directories.

Might be worth adding a brief message to tell people to clone manually instead of via the learn.co open button.

**Comment by maxwellbenton** [comment]
Hi @clintonn,

This issue seems to have occurred specifically for this lesson. While I am unable to replicate, I can confirm that this lesson is now working as expected. The MP3 files have also been removed as part of a recent update.
