### ISSUE TITLE
Advanced Jukebox cannot be completed on IDE

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/jukebox-cli#36]
I don't think that the advanced Jukebox would work with the IDE, given that the IDE command line cannot open system applications on the user's computer (or at least, I don't think it would be able to?). If that is the case, this should be noted in the README.

**Comment by maxwellbenton** [comment]
Hi @kwebster2,

Thank you for providing this feedback. This lesson has been simplified and the advanced jukebox content has been removed. This repository has been updated and aligned with a newer version that is present in newest prework.
