### ISSUE TITLE
missing require statement in spec_helper

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/jukebox-cli#39]
require_relative '../lib/advanced_jukebox' 
require_relative '../lib/jukebox'

**Comment by maxwellbenton** [comment]
Hi @d-d-d-dalia!

Thanks for opening this issue! This lesson has recently been updated and simplified so that there is no advanced jukebox. `spec_helper.rb` now only needs to require `../lib/jukebox`, and everything should be working with the recent updates.

Hope you have a good day!
