### ISSUE TITLE
Won't let me submit

### ISSUE THREAD

**Issue by claudifox** [learn-co-curriculum/jukebox-cli#40]
I have passed all the tests using "learn", tried to submit it with "learn submit" but isn't working. The code is on my GitHub though.

**Comment by maxwellbenton** [comment]
Hi @claudifox,

Sorry to hear that this happened! I am unfortunately unable to replicate this issue, but can confirm that this lesson is currently working and has been recently updated.

We apologize for any frustration this may have caused you. If you do not believe that this issue has been addressed, please re-open this issue. 💙
