### ISSUE TITLE
Inaccurate mention of chomp in instructions README

### ISSUE THREAD

**Issue by WSINTRA** [learn-co-curriculum/jukebox-cli#41]
Hi, in the Jukebox instructions the following statement is made.

When we run ruby lib/jukebox.rb, it's going to print out Enter your name:, then the Terminal prompt will return, and you'll type in your name. The user input is obtained by the gets method, then any trailing whitespace gets removed via the chomp method, and finally the result is stored in the users_name local variable (let's assume users_name = "Avi Flombaum"). Finally, the program will print out the output of the say_hello method, which is "Hi, Avi Flombaum!".

However the chomp method does not remove trailing whitespace, that is what the strip method is for.

**Comment by maxwellbenton** [comment]
Hi @WSINTRA,

Thank you for opening this issue! We've updated this lesson's readme and incorporated changes based on the feedback you provided, replacing `chomp` with `strip` and adding an explanation of how it `strip` works

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
